# Generated by Django 4.1.4 on 2023-09-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=3)),
                ('Highest_Education', models.CharField(choices=[('grade 12', 'Grade 12'), ('diploma', 'Diploma'), ('bachelors degree', 'Bachelors Degree'), ('masters degree', 'Masters Degree'), ('phd', 'PhD')], default='Choose', max_length=16)),
                ('Institute', models.CharField(max_length=100)),
                ('study', models.CharField(max_length=20)),
                ('work_experience', models.CharField(max_length=20)),
                ('institute_did_you_get_admitted_to_in_Canada', models.CharField(max_length=100)),
                ('program_of_study_in_Canada', models.CharField(max_length=20)),
                ('country_are_you_applying_from', models.CharField(max_length=20)),
                ('future_goals', models.CharField(max_length=30)),
                ('English_Listening', models.CharField(max_length=5)),
                ('English_Reading', models.CharField(max_length=5)),
                ('English_Speaking', models.CharField(max_length=5)),
                ('English_Writing', models.CharField(max_length=5)),
                ('Did_you_pay_your_first_year_tuition', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=5)),
                ('How_much_tuition_fee_did_you_pay', models.CharField(max_length=7)),
                ('Did_you_do_a_GIC', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=5)),
                ('How_much_did_you_pay_towards_GIC', models.CharField(max_length=7)),
            ],
        ),
    ]
