# Generated by Django 4.1.4 on 2023-09-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='Did_you_do_a_GIC',
            new_name='did_you_do_a_GIC',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='Did_you_pay_your_first_year_tuition',
            new_name='did_you_pay_your_first_year_tuition',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='country_are_you_applying_from',
            new_name='do_you_have_any_relevant_work_experience',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='English_Listening',
            new_name='english_scores_listening',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='English_Reading',
            new_name='english_scores_reading',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='English_Speaking',
            new_name='english_scores_speaking',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='English_Writing',
            new_name='english_scores_writing',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='Highest_Education',
            new_name='highest_level_of_education',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='How_much_did_you_pay_towards_GIC',
            new_name='how_much_did_you_pay_towards_GIC',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='How_much_tuition_fee_did_you_pay',
            new_name='how_much_tuition_fee_did_you_pay',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='Institute',
            new_name='institute_where_you_completed_your_highest_level_of_education',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='future_goals',
            new_name='what_are_your_future_goals',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='program_of_study_in_Canada',
            new_name='what_did_you_study',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='institute_did_you_get_admitted_to_in_Canada',
            new_name='what_institute_did_you_get_admitted_to_in_Canada',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='study',
            new_name='what_is_your_program_of_study_in_Canada',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='work_experience',
            new_name='which_country_are_you_applying_from',
        ),
        migrations.AlterField(
            model_name='form',
            name='age',
            field=models.IntegerField(max_length=3),
        ),
    ]
