# Generated by Django 4.1.4 on 2023-09-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_did_you_do_a_gic_form_did_you_do_a_gic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='age',
            field=models.IntegerField(),
        ),
    ]
